In [3]:
import pandas as pd
import numpy as np

In [5]:
stud_df = pd.DataFrame([
    ["hetvi","bca",8],
    ["mahek","bsc",8.5],
    ["ria","bba",7.5],
    ["yagnik","diplo",8],
    ["om","pharma",7.7]
],columns=['name','stream','cgpa'])

print(stud_df)

     name  stream  cgpa
0   hetvi     bca   8.0
1   mahek     bsc   8.5
2     ria     bba   7.5
3  yagnik   diplo   8.0
4      om  pharma   7.7

In [6]:
stud_df.cgpa.value_counts()

cgpa
8.0    2
8.5    1
7.5    1
7.7    1
Name: count, dtype: int64

In [10]:

data_path = r"D:\BCA SEM 5\DV\lab\03 ipl_matches (1).xlsx"
ipl = pd.read_excel(data_path)
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007-08-01 00:00:00,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007-08-01 00:00:00,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007-08-01 00:00:00,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007-08-01 00:00:00,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007-08-01 00:00:00,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [11]:
ipl[
    (ipl['MatchNumber'] == 'Final') |
    (ipl['MatchNumber'] == 'Qualifier 1')|
    (ipl['MatchNumber'] == 'Qualifier 2')
]  ['Player_of_Match'].value_counts()

Player_of_Match
JJ Bumrah            2
KA Pollard           2
M Vijay              2
YK Pathan            2
SK Raina             2
HH Pandya            1
JC Buttler           1
DA Miller            1
F du Plessis         1
VR Iyer              1
RD Gaikwad           1
TA Boult             1
MP Stoinis           1
SR Watson            1
KH Pandya            1
KV Sharma            1
Washington Sundar    1
BCJ Cutting          1
DA Warner            1
AB de Villiers       1
RG Sharma            1
A Nehra              1
MK Pandey            1
V Sehwag             1
UT Yadav             1
Harbhajan Singh      1
MEK Hussey           1
MS Bisla             1
CH Gayle             1
A Kumble             1
Name: count, dtype: int64

In [13]:
s = pd.Series([1, 5, 7, 9, 5, 3, 4, 6, 2, 8])


s.sort_values(ascending = False)

3    9
9    8
2    7
7    6
4    5
1    5
6    4
5    3
8    2
0    1
dtype: int64

In [16]:
ipl.sort_values(by = 'City', ascending = False)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
472,829743,Visakhapatnam,2015-04-22,2015,19,Sunrisers Hyderabad,Kolkata Knight Riders,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Kolkata Knight Riders,field,N,Sunrisers Hyderabad,Runs,16.0,D/L,DA Warner,"['S Dhawan', 'DA Warner', 'RS Bopara', 'NV Ojh...","['RV Uthappa', 'G Gambhir', 'MK Pandey', 'AD R...",RK Illingworth,VA Kulkarni
195,1181767,Visakhapatnam,2019-05-10,2019,Qualifier,Delhi Capitals,Chennai Super Kings,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,6.0,NaN,F du Plessis,"['PP Shaw', 'S Dhawan', 'C Munro', 'SS Iyer', ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ...",BNJ Oxenford,S Ravi
696,548311,Visakhapatnam,2012-04-07,2012,6,Deccan Chargers,Chennai Super Kings,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Deccan Chargers,field,N,Chennai Super Kings,Runs,74.0,NaN,RA Jadeja,"['DJ Harris', 'S Dhawan', 'PA Patel', 'CL Whit...","['M Vijay', 'F du Plessis', 'SK Raina', 'S Bad...",JD Cloete,HDPK Dharmasena
387,980993,Visakhapatnam,2016-05-15,2016,47,Mumbai Indians,Delhi Daredevils,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Delhi Daredevils,field,N,Mumbai Indians,Runs,80.0,NaN,KH Pandya,"['RG Sharma', 'MJ Guptill', 'KH Pandya', 'KA P...","['MA Agarwal', 'Q de Kock', 'KK Nair', 'SV Sam...",Nitin Menon,CK Nandan
693,548314,Visakhapatnam,2012-04-09,2012,9,Deccan Chargers,Mumbai Indians,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Deccan Chargers,bat,N,Mumbai Indians,Wickets,5.0,NaN,RG Sharma,"['PA Patel', 'S Dhawan', 'B Chipli', 'DT Chris...","['TL Suman', 'RE Levi', 'RG Sharma', 'AT Rayud...",AK Chaudhary,JD Cloete
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,729295,NaN,2014-04-22,2014,9,Kings XI Punjab,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,N,Kings XI Punjab,Runs,72.0,NaN,GJ Maxwell,"['CA Pujara', 'V Sehwag', 'GJ Maxwell', 'DA Mi...","['AJ Finch', 'S Dhawan', 'DA Warner', 'KL Rahu...",M Erasmus,S Ravi
545,729291,NaN,2014-04-20,2014,7,Rajasthan Royals,Kings XI Punjab,Sharjah Cricket Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,7.0,NaN,GJ Maxwell,"['AM Nayar', 'AM Rahane', 'SV Samson', 'SR Wat...","['CA Pujara', 'V Sehwag', 'WP Saha', 'GJ Maxwe...",BF Bowden,M Erasmus
546,729289,NaN,2014-04-19,2014,6,Kolkata Knight Riders,Delhi Daredevils,Dubai International Cricket Stadium,Kolkata Knight Riders,bat,N,Delhi Daredevils,Wickets,4.0,NaN,JP Duminy,"['JH Kallis', 'G Gambhir', 'MK Pandey', 'RV Ut...","['M Vijay', 'MA Agarwal', 'KD Karthik', 'LRPL ...",Aleem Dar,VA Kulkarni
547,729287,NaN,2014-04-19,2014,5,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,7.0,NaN,PA Patel,"['NJ Maddinson', 'PA Patel', 'V Kohli', 'Yuvra...","['MEK Hussey', 'AP Tare', 'AT Rayudu', 'RG Sha...",Aleem Dar,AK Chaudhary
550,729281,NaN,2014-04-17,2014,2,Delhi Daredevils,Royal Challengers Bangalore,Sharjah Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,8.0,NaN,YS Chahal,"['MA Agarwal', 'M Vijay', 'KD Karthik', 'MK Ti...","['PA Patel', 'NJ Maddinson', 'V Kohli', 'Yuvra...",Aleem Dar,S Ravi

In [21]:
batsman = r"D:\BCA SEM 5\DV\lab\00 batsman_runs_ipl.xlsx"
batsman = pd.read_excel(batsman)
batsman

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [22]:
batsman['batsman_run'].rank(ascending = False)

0      166.5
1      226.0
2      535.0
3      329.0
4      402.5
       ...
600    594.0
601    343.0
602    547.5
603     27.0
604    256.0
Name: batsman_run, Length: 605, dtype: float64

In [24]:
students = pd.DataFrame(
    {
        'name':['nitish','ankit','rupesh','harshit','mrityunjay','jenish','rishabh','parth','aditya','khilan'],
        'college':['bit','iit','vit','gmers','psmc','vlsi','ssit','ld','gsms','git'],
        'branch':['eee','it','cse','mbbs','me','ce','civ','cse','bio','mba'],
        'cgpa':[6.66,8.25,6.41,8,5.6,9.0,7.4,10,7.4,7.8],
        'package':[4,5,6,10,6,7,8,9,11,9.5]

    }
)
students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3     harshit   gmers   mbbs   8.00     10.0
4  mrityunjay    psmc     me   5.60      6.0
5      jenish    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7       parth      ld    cse  10.00      9.0
8      aditya    gsms    bio   7.40     11.0
9      khilan     git    mba   7.80      9.5

In [25]:
cols = {'name': 'student', 'college': 'institute'}

students.rename(columns=cols)

      student institute branch   cgpa  package
0      nitish       bit    eee   6.66      4.0
1       ankit       iit     it   8.25      5.0
2      rupesh       vit    cse   6.41      6.0
3     harshit     gmers   mbbs   8.00     10.0
4  mrityunjay      psmc     me   5.60      6.0
5      jenish      vlsi     ce   9.00      7.0
6     rishabh      ssit    civ   7.40      8.0
7       parth        ld    cse  10.00      9.0
8      aditya      gsms    bio   7.40     11.0
9      khilan       git    mba   7.80      9.5

In [26]:
data = pd.Series([1, 2, 3, 4, 5, 1, 2, 5, 55, 45, 65, 75, np.nan, np.nan, np.nan])

data.unique()

array([ 1.,  2.,  3.,  4.,  5., 55., 45., 65., 75., nan])

In [27]:
ipl['Season'].unique()

array([2022, 2021, '2020/21', 2019, 2018, 2017, 2016, 2015, 2014, 2013,
       2012, 2011, datetime.datetime(2009, 10, 1, 0, 0), 2009,
       datetime.datetime(2007, 8, 1, 0, 0)], dtype=object)

In [28]:
data

0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
5      1.0
6      2.0
7      5.0
8     55.0
9     45.0
10    65.0
11    75.0
12     NaN
13     NaN
14     NaN
dtype: float64

In [29]:

data.nunique()

9

In [30]:
ipl['Season'].nunique()

15

In [31]:
ipl.isnull()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
946,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
947,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
948,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
949,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False

In [32]:
ipl['method']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
945    NaN
946    NaN
947    NaN
948    NaN
949    NaN
Name: method, Length: 950, dtype: str

In [33]:
len(ipl)

950

In [34]:
ipl.dropna(inplace= True)

In [35]:
len(ipl)

19

In [36]:
s = pd.Series([1, 2, 3, 4, 5, np.nan, 6, 7, np.nan, 8, 9])
s

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     NaN
6     6.0
7     7.0
8     NaN
9     8.0
10    9.0
dtype: float64

In [37]:
s.fillna(100)

0       1.0
1       2.0
2       3.0
3       4.0
4       5.0
5     100.0
6       6.0
7       7.0
8     100.0
9       8.0
10      9.0
dtype: float64

In [38]:
data = {
    'Name': ['Nikunj', 'Jugal', 'Harshit', 'Jenish', 'Jugal', 'Harshit', 'Parth', 'Jenish', 'Parth'],
    'Surname': ['Bosamiya', 'Bosamiya', 'Kamani', 'Mer', 'Bosamiya', 'Kamani', 'Paghdar', 'Mer', 'Paghdar'],
    'City': ['Jetpur', 'Rajkot', 'Himmatnagar', 'Anand', 'Rajkot', 'Himmatnagar', 'Jetpur', 'Ahmedabad', 'Vadodara']
}

friends = pd.DataFrame(data)

In [39]:
friends

      Name   Surname         City
0   Nikunj  Bosamiya       Jetpur
1    Jugal  Bosamiya       Rajkot
2  Harshit    Kamani  Himmatnagar
3   Jenish       Mer        Anand
4    Jugal  Bosamiya       Rajkot
5  Harshit    Kamani  Himmatnagar
6    Parth   Paghdar       Jetpur
7   Jenish       Mer    Ahmedabad
8    Parth   Paghdar     Vadodara

In [40]:
friends.drop_duplicates()

      Name   Surname         City
0   Nikunj  Bosamiya       Jetpur
1    Jugal  Bosamiya       Rajkot
2  Harshit    Kamani  Himmatnagar
3   Jenish       Mer        Anand
6    Parth   Paghdar       Jetpur
7   Jenish       Mer    Ahmedabad
8    Parth   Paghdar     Vadodara